[package]
name = "crowbar"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["wayland"] }
glam = "0.29.2"
once_cell = "1.20.2"
vulkano = "0.34.1"
vulkano-shaders = "0.34.0"
winit = { version = "0.30.5", features = ["rwh_04", "rwh_05"] }
